default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root        # your MySQL username
  password: root         # your MySQL password
  host: localhost

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
  username: <%= ENV["TODO_API_DATABASE_USERNAME"] %>
  password: <%= ENV["TODO_API_DATABASE_PASSWORD"] %>
